### ISSUE TITLE
Keep main.cpp clean

### ISSUE THREAD

**Issue by TheZitroX** [jondurrant/RPIPicoWeatherStation#2]
Avoid too many functions in main and refactor them in a separate unit or class.
Use space only instead of tabs.

**Comment by jondurrant** [comment]
Currently refactoring

**Comment by TheZitroX** [comment]
:160 statusAgent(...) expects uint8_t, use constexpr uint8_t instead of #define. It guarantees that the values are evaluated at compile-time, making them truly constant and enabling optimizations.
